<?php

/**
 * Default Layout
 *  
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype() 
?>

<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

		<?php 
				echo $this->headTitle($this->title);
	    echo $this->headLink()->appendStylesheet('/styles/error.css');
	    ?>

	</head>
	
	<body>
		<!-- Box -->
		<div id="box">
		<div id="header_in">
				<div id="headline">
				</div>
		</div>
			
			
		<!-- content -->
		<div id="content">
			<?php echo $this->layout()->content ?>
			<br />
			 
		</div>
		</div>
		<br>
	</body>

</html>
