<?php
/**
 * Default Layout for all pages except error pages and login page
 *
 * Layout is based on BOOTSTRAP, build by twitter: 
 * http://twitter.github.com/bootstrap/
 *
 * @author Alexander Schmalzhaf
 * @version 2/2012 (2012-05-11)
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="TRP">
        <meta name="author" content="Südwestdeutscher EC-Verband, www.SWDEC.de">

        <!-- Le styles -->
        <link href="/styles/bootstrap.css" rel="stylesheet">
        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
        <link href="/styles/bootstrap-responsive.css" rel="stylesheet">
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet">
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php
        echo $this->headTitle($this->title);
        $this->headLink()->appendStylesheet('/styles/main_v1.css');
        $this->headLink()->appendStylesheet('/styles/table_v1.css');
        echo $this->headLink();
        ?>

        <!-- Favicon -->
        <link rel="shortcut icon" href="/images/favicon_v1.ico">

        <!--Scripte möglicherweise später ans Ende verschieben-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js"></script>
    </head>

    <body>
        <!--
        <div id="headline">
            <div id="ajaxIcon" style="display: none;">
                <center>
                    <img src="/images/ajax-loader.gif">
                </center>
            </div>
        </div>
        -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">

                    <a class="brand" href="/Basic/Index">Teennight 2013</a>

                    <div class="nav-collapse">


                        <ul class="nav pull-right"> 
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="icon-user icon-white"></i> 
                                    <?php
                                    $user = $this->placeholder('user');
                                    echo $user['fname'];
                                    echo ' ';
                                    echo $user['lname'];
                                    ?>

                                    <span class="caret"></span>

                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="/Basic/changeaccount">Profil bearbeiten</a></li>
                                    <li><a href="/Basic/changepassword">Passwort ändern</a></li>
                                    <li class="divider"></li>
                                    <li><a href="/Login/logout">Ausloggen</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div id="message-container" class="nav pull-right">
                            <!-- Neue Nachrichten werden via Javascript hier eingefügt -->
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="container-fluid">

            <div class="row-fluid">
                <div class="span2">
                    <?php echo $this->placeholder('mainmenu') ?>
                </div>
                <div class="span10">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="/scripts/main_v1.js"></script>
        <script src="/scripts/bootstrap-transition.js"></script>
        <script src="/scripts/bootstrap-alert.js"></script>
        <script src="/scripts/bootstrap-modal.js"></script>
        <script src="/scripts/bootstrap-dropdown.js"></script>
        <script src="/scripts/bootstrap-scrollspy.js"></script>
        <script src="/scripts/bootstrap-tab.js"></script>
        <script src="/scripts/bootstrap-tooltip.js"></script>
        <script src="/scripts/bootstrap-popover.js"></script>
        <script src="/scripts/bootstrap-button.js"></script>
        <script src="/scripts/bootstrap-collapse.js"></script>
        <script src="/scripts/bootstrap-carousel.js"></script>
        <script src="/scripts/bootstrap-typeahead.js"></script>

    </body>
</html>