<?php echo $this->headScript()->appendFile('/scripts/jquery_validate.js')?>
<script type="text/javascript">
$(function() {

	$("document").ready(function(){
		
		$("#pwdform").validate({
			rules: {
				pwd: {
					required: true,
					minlength: 5 },
				confirm_pwd: {
					required: true,
					minlength: 5,
					equalTo: "#form_pwd"}
			},
			messages: {
				pwd: {
					required: "Bitte Passwort eingeben",
					minlength: "Das Passwort muss mind. 5 Zeichen lang sein"},
				confirm_pwd: {
					required: "Bitte Passwort eingeben",
					minlength: "Das Passwort muss mind. 5 Zeichen lang sein",
					equalTo: "Das Passwort stimmt nicht &uuml;berein!"}	
			}	
		});
		
	//ready to start...	
	});
	
});
</script >

<h3>Das Passwort muss aus mindestens 5 Zeichen bestehen!</h3>

<div style="float:left;">
<form id="pwdform" action="/Basic/updatepassword" method="post"  >
	<div class="inputbox">
		<label for="form_pwd" class="formlabel">Passwort</label>
		<input id="form_pwd" type="password" name="pwd" value="" />
	</div>
	<p>&nbsp;</p>
	<div class="inputbox">
		<label for="form_confirm_pwd" class="formlabel">Passwort wiederholen</label>
		<input id="form_confirm_pwd" type="password" name="confirm_pwd" value="" />
	</div>
	<p>&nbsp;</p>
	<div class="inputbox">
		<input id="change_button" type="submit" value="Passwort &auml;ndern" /> 
	</div>
</form>
</div>



