<div class="container-fluid">
    <div class="row-fluid">
        <div class="span8">

            <div id="myCarousel" class="carousel slide">
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="active item">
                        <img src="/images/tn-praesentation/1.jpg">
                        <div class="carousel-caption">
                            <h4>Die Teennight...</h4>
                            <p>...auch dieses Jahr - 2013 - erwarten wir wieder mehr als 1000 Teens!</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="/images/tn-praesentation/2.jpg">
                        <div class="carousel-caption">
                            <h4>Action vom Feinsten...</h4>
                            <p>...die besten Aktionen, die coolsten Attraktionen, die abgefahrensten Ideen. Alles dabei. 
                                Teennight eben.</p>
                            </div>
                        </div>
                        <div class="item">
                            <img src="/images/tn-praesentation/3.jpg">
                            <div class="carousel-caption">
                                <h4>Und nun kommst DU...</h4>
                                <p>...was wäre die Teennight ohne dich? Du bist MITARBEITER! Schon jetzt: DANKE.
                                    Wofür...?</p>
                                </div>
                            </div>
                            <div class="item">
                                <img src="/images/tn-praesentation/4.jpg">
                                <div class="carousel-caption">
                                    <h4>Dass du dir Zeit nimmst...</h4>
                                    <p>...für die Teens, deinen Feierabend opferst, um unseren Teens eine geniale Nacht zu reißen. 
                                        Dass du auch ein offenes Ohr hast für Fragen, Sorgen und Nöte.</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="/images/tn-praesentation/5.jpg">
                                    <div class="carousel-caption">
                                        <h4>Dass deine Hände...</h4>
                                        <p>...zum Beispiel helfen, mehr als 1300 Menschen gut, satt und glücklich durch die Nacht zu bringen.</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="/images/tn-praesentation/6.jpg">
                                    <div class="carousel-caption">
                                        <h4>Dass dein Hirn...</h4>
                                        <p>...mitdenkt, auch wenn's spät wird. Nachts ist's nacht und spät ist's spät. Auch für Teens. Danke, dass du mit aufpasst.</p>
                                    </div>
                                </div>
                            </div>
                            <!-- Carousel nav -->
                            <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                            <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                        </div>


                        <h1>Herzlich willkommen zur Teennight 2013!</h1>

                        <span style="font-size: 12pt;"><br>
                            <div class="alert alert-success">
                                <p><strong>Infos für Freitag</strong></p>
                                <p>Bald geht's los mit unserer Teennight 2013. WANN geht's für dich los...?</p>
                                <br />
                                <p><strong>19:00 Uhr</strong> | Kleiner Imbiss für Mitarbeiter [für alle, die mögen...]</p>
                                <p><strong>19:30 Uhr</strong> | Mitarbeiterbesprechung [FÜR ALLE MITARBEITER WICHTIG]</p>
                                <br />
                                <p>Und WO...?</p>
                                <p>...im großen Tagungsraum im EC Freizeitzentrum Dobel</p>
                                <br />
                                <p>Danke, dass du pünktlich zur Mitarbeiterbesprechung da sein wirst. Das hilft sehr, diesen genialen, aber doch planerisch recht anspruchsvollen Abend sauber durchzuziehen.</p>
                                <p>Let's have fun...!</p>
                            </div>
                            <strong>Vielen Dank</strong>, dass du als Mitarbeiter dabei bist...
                            <br><br>
                            ... und dass du dir Zeit nimmst, <a href="/Basic/changeaccount">deine Daten hier zu kontrollieren und einzugeben! </a>
                            <br><br>
                            Das erspart uns viel Arbeit bei der Teennight.

                            <br><br>
                            Vergiss außerdem nicht, <a href="/Basic/wishlist">deine W&uuml;nsche für die Aktionen </a>, an denen du mitarbeiten willst, einzutragen!

                        </span>
                    </div>
                </div>
            </div>