<script type="text/javascript">
$(function() {

})
</script>

Du hast deine Zugangsdaten vergessen?<br/>

<div class="control-group">
    <label for="form_fname" class="control-label">Mail-Adresse:</label>
    <div class="controls trpichange">
        <input class="" id="form_mail" type="text" name="mail" value="" />
    </div>
</div>
<br/>
<div style="">
    <button class="btn btn-info" id="" type="submit">Neues Passwort anfordern</button>
    <br/>
    <br/>
    <p><a href="/Login/index">Zurück zum Login...</a></p>
</div>